everify/urls.py
from django.conf.urls import url

from . import views

app_name = 'everify'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
]

institutions/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required, permission_required
from . import views

app_name = 'institutions'

urlpatterns = [
   url(r'^login/$', views.LoginView.as_view(), name='login'),
   url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
   url(r'^register/$', views.RegisterView.as_view(), name='register'),
   url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
]

verification/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('everify.urls', namespace='everify')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^institutions/', include('institutions.urls', namespace='institutions')),
]

institutions/models.py
from django.db import models

# Create your models here.

institutions/forms.py
import django
from django import forms
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.hashers import identify_hasher
from django.contrib.auth.forms import ReadOnlyPasswordHashField, ReadOnlyPasswordHashWidget, AuthenticationForm as DjangoAuthenticationForm, PasswordResetForm as OldPasswordResetForm
from django.utils.translation import ugettext_lazy as _, ugettext
from django.utils.html import format_html
from django.forms import formset_factory

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field, Fieldset, ButtonHolder
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions

from everify.models import UniversityInfo

User = get_user_model()


class UserLoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
       
        # user_qs = User.objects.filter(username=username)
        # if user_qs.count() == 1:
        #     user = user_qs.first()
        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect passsword")
            if not user.is_active:
                raise forms.ValidationError("This user is no longer active.")
        return super(UserLoginForm, self).clean(*args, **kwargs)

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-8'
    helper.layout = Layout(
        Field('email', css_class='form-control'),
        Field('password', css_class='form-control'),
        HTML("<hr>"),
        FormActions(
            Submit('register', 'Regster', css_class="btn btn-template-main"),
        )
    )



class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email')
    email2 = forms.EmailField(label='Confirm Email')
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = [
            'name',
            'email',
            'email2',
            'password',
            'password2'
        ]

    def clean_email2(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        return email

    def clean_password2(self, *args, **kwargs):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Passwords must match")
        return password

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-8'
    helper.layout = Layout(
        Field('name', css_class='form-control'),
        Field('email', css_class='form-control'),
        Field('email2', css_class='form-control'),
        Field('password', css_class='form-control'),
        Field('password2', css_class='form-control'),
        #HTML("<hr>"),
        #FormActions(
        #    Submit('register', 'Regster', css_class="btn btn-template-main"),
        #)
    )

class UserProfileForm(forms.ModelForm):
    name = forms.CharField(label='Full Name')
    institute_name = forms.CharField(label='Name of Institution')
    category = forms.CharField(label='Institution Category')
    url = forms.URLField(label='Website')
    contact = forms.CharField(label='Contact Number')
    address = forms.CharField(label='Address')
    region = forms.CharField(label='Region')
    location = forms.CharField(label='Location')
    country = forms.CharField(label='Country')
    verification_amount = forms.IntegerField(label="Verification Amount")
    photo = forms.ImageField(label="Institutiion Logo")

    class Meta:
        model = UniversityInfo
        fields = [
            'institute_name',
            'category',
            'url',
            'contact',
            'address',
            'region',
            'location',
            'country',
            'verification_amount',
            'photo'
        ]

    """
    def clean_email2(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        return email

    def clean_password2(self, *args, **kwargs):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Passwords must match")
        return password
    """


    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-8'
    helper.layout = Layout(
        Field('institute_name', css_class='form-control'),
        Field('category', css_class='form-control'),
        Field('url', css_class='form-control'),
        Field('contact', css_class='form-control'),
        Field('address', css_class='form-control'),
        Field('region', css_class='form-control'),
        Field('location', css_class='form-control'),
        Field('country', css_class='form-control'),
        Field('verification_amount', css_class='form-control'),
        Field('photo', css_class='form-control'),
        #HTML("<hr>"),
        #FormActions(
        #    Submit('register', 'Regster', css_class="btn btn-template-main"),
        #)
    )

RegisterFormSet = formset_factory(UserRegisterForm)
ProfileFormSet = formset_factory(UserProfileForm)

institutions/views.py
import json
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.conf import settings
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import resolve, reverse, reverse_lazy
from django.shortcuts import redirect, render
from django.views import generic
from django.views.generic import FormView, TemplateView, RedirectView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import UserLoginForm, UserRegisterForm, UserProfileForm

User = get_user_model()


class LoginView(FormView):
    template_name = 'institutions/institution_login.html'
    form_class = UserLoginForm
    
    def form_valid(self, form):
        if self.request.method == 'POST':
            form = UserLoginForm(self.request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("email")
                password = form.cleaned_data.get('password')
                user = authenticate(email=username, password=password)
                if user is not None:
                    login(self.request, user)

        return super(LoginView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        #context['form'] = self.get_form()
        context.update({
            'form': self.get_form(),
        })
        return context
    
    def get_success_url(self):
        return reverse('institutions:dashboard')

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            return redirect(self.get_success_url())
        return super(LoginView, self).dispatch(*args, **kwargs)

class LogoutView(RedirectView):
    template_name = None
    permanent = False
    
    def get_redirect_url(self, *args, **kwargs):
        super(LogoutView, self).get_redirect_url(*args, **kwargs)
        return reverse('everify:home')

    def get(self, *args, **kwargs):
        logout(self.request)
        # If we have a url to redirect to, do it. Otherwise render the logged-out template.
        if self.get_redirect_url(**kwargs):
            return RedirectView.get(self, *args, **kwargs)
        
        return redirect("/")

class RegisterView(FormView, TemplateView):
    template_name = 'everify/institution_register.html'
    form_class = UserRegisterForm
    second_form_class = UserProfileForm
    
    def form_valid(self, request, *args, **kwargs):
        if self.request.method == 'POST':
            register_formset = RegisterFormSet(self.request.POST, self.request.FILES, prefix='register')
            profile_formset = ProfileFormSet(self.request.POST, self.request.FILES, prefix='profile')
            if register_formset.is_valid() and profile_formset.is_valid():
                user = register_formset.save(commit=False)
                profile = profile_formset.save()
                password = register_formset.cleaned_data.get('password')
                user.set_password(password)
                user.save()
                new_user = authenticate(username=user.email, password=password)
                login(self.request, new_user)
            else:
                register_formset = RegisterFormSet(prefix='register')
                profile_formset = ProfileFormSet(prefix='profile')
            
        return super(RegisterView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context.update({
            'register_formset': register_formset,
            'profile_formset':  profile_formset,
        })
        return context

    def get_success_url(self):
        return reverse('institutions:dashboard')

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            return redirect(self.get_success_url())
        return super(RegisterView, self).dispatch(*args, **kwargs)



#@login_required
#@permission_required('polls.can_vote', raise_exception=True)

#@login_required(login_url='/institutions/login/')  #redirect_field_name='my_redirect_field'
@method_decorator(login_required(login_url='/institutions/login/'), name='dispatch')
class DashboardView(generic.TemplateView):
    model = None
    template_name = 'institutions/dashboard_institutions.html'

institutions/templates/institutions/dashboard_institutions.html
<!DOCTYPE html>
<html lang="en">
  {% load staticfiles %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> Institutions </title>

    <!-- Bootstrap -->
    <link href="{% static 'everify/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'everify/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'everify/css/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'everify/css/green.css' %}" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="{% static 'everify/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'everify/css/daterangepicker.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'everify/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Institution</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile">
              <div class="profile_pic">
                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="index.html">Dashboard</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-edit"></i> Certificate Management <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="form.html">Upload Certificates</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="chartjs.html">Chart JS</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
          

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt="">{{ user.name }}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">0%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="{% url 'institutions:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>

              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <!-- top tiles -->
          <div class="row tile_count">
            
          </div>
          <!-- /top tiles -->

          {% block content %}

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="dashboard_graph">

                <div class="row x_title">
                  <div class="col-md-6">
                    <h3>Verification Activities <small> certfificates </small></h3>
                  </div>
                  <div class="col-md-6">

                  </div>
                </div>

                <div class="col-md-9 col-sm-9 col-xs-12">
                  <div id="placeholder33" style="height: 260px; display: none" class="demo-placeholder"></div>
                  <div style="width: 100%;">
                    <div id="canvas_dahs" class="demo-placeholder" style="width: 100%; height:270px;"></div>
                  </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12 bg-white">

                </div>
                <div class="clearfix"></div>
              </div>
            </div>

          </div>
          <br />
       
        {% endblock %}
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Institutions - instititional Examination Centre <a href="">   </a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'everify/js/jquery-2.2.4min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'everify/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'everify/js/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'everify/js/nprogress.js' %}"></script>
    <!-- Chart.js -->
    <script src="{% static 'everify/js/Chart.min.js' %}"></script>
    <!-- gauge.js -->
    <script src="{% static 'everify/js/gauge.min.js' %}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{% static 'everify/js/bootstrap-progressbar.min.js' %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static 'everify/js/moment.min.js' %}"></script>
    <script src="{% static 'everify/js/daterangepicker.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'everify/js/custom.min.js' %}"></script>

    
    <!-- bootstrap-daterangepicker -->
    <script>
      $(document).ready(function() {

        var cb = function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
          $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        };

        var optionSet1 = {
          startDate: moment().subtract(29, 'days'),
          endDate: moment(),
          minDate: '01/01/2012',
          maxDate: '12/31/2015',
          dateLimit: {
            days: 60
          },
          showDropdowns: true,
          showWeekNumbers: true,
          timePicker: false,
          timePickerIncrement: 1,
          timePicker12Hour: true,
          ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
          },
          opens: 'left',
          buttonClasses: ['btn btn-default'],
          applyClass: 'btn-small btn-primary',
          cancelClass: 'btn-small',
          format: 'MM/DD/YYYY',
          separator: ' to ',
          locale: {
            applyLabel: 'Submit',
            cancelLabel: 'Clear',
            fromLabel: 'From',
            toLabel: 'To',
            customRangeLabel: 'Custom',
            daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            firstDay: 1
          }
        };
        $('#reportrange span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
        $('#reportrange').daterangepicker(optionSet1, cb);
        $('#reportrange').on('show.daterangepicker', function() {
          console.log("show event fired");
        });
        $('#reportrange').on('hide.daterangepicker', function() {
          console.log("hide event fired");
        });
        $('#reportrange').on('apply.daterangepicker', function(ev, picker) {
          console.log("apply event fired, start/end dates are " + picker.startDate.format('MMMM D, YYYY') + " to " + picker.endDate.format('MMMM D, YYYY'));
        });
        $('#reportrange').on('cancel.daterangepicker', function(ev, picker) {
          console.log("cancel event fired");
        });
        $('#options1').click(function() {
          $('#reportrange').data('daterangepicker').setOptions(optionSet1, cb);
        });
        $('#options2').click(function() {
          $('#reportrange').data('daterangepicker').setOptions(optionSet2, cb);
        });
        $('#destroy').click(function() {
          $('#reportrange').data('daterangepicker').remove();
        });
      });
    </script>
    <!-- /bootstrap-daterangepicker -->

    <!-- gauge.js -->
    <script>
      var opts = {
          lines: 12,
          angle: 0,
          lineWidth: 0.4,
          pointer: {
              length: 0.75,
              strokeWidth: 0.042,
              color: '#1D212A'
          },
          limitMax: 'false',
          colorStart: '#1ABC9C',
          colorStop: '#1ABC9C',
          strokeColor: '#F0F3F3',
          generateGradient: true
      };
      var target = document.getElementById('foo'),
          gauge = new Gauge(target).setOptions(opts);

      gauge.maxValue = 6000;
      gauge.animationSpeed = 32;
      gauge.set(3200);
      gauge.setTextField(document.getElementById("gauge-text"));
    </script>
    <!-- /gauge.js -->
  </body>
</html>

institutions/templates/institutions/institution_login.html
<!DOCTYPE html>
<html lang="en">
 {% load staticfiles %}
 <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Institution Login | </title>

    <!-- Bootstrap -->
    <link href="{% static 'everify/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'everify/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'everify/css/nprogress.css' %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static 'everify/css/animate.min.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'everify/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form action="{% url 'institutions:login' %}" method="POST">
              {% csrf_token %}  
              {{ form.non_field_errors }}
              <h1>Login Form</h1>
              <div>
                <input type="email" class="form-control" name="email" placeholder="Username" required="" />
              </div>
              <div>
                <input type="password" class="form-control" name="password" placeholder="Password" required="" />
              </div>
              <div>
                <button class="btn btn-default submit" type="submit" value="submit">Log in</button>
                <a class="reset_pass" href="#">Lost your password?</a>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">New to site?
                  <a href="{% url 'institutions:register' %}" class="to_register"> Create Account </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1>Institutional Login</h1>
                  <p>©2016 All Rights Reserved. Everify. Privacy and Terms</p>
                </div>
              </div>
            </form>
          </section>
        </div>
        
      </div>
    </div>
  </body>
</html>