everify/urls.py
from django.conf.urls import url

from . import views

app_name = 'everify'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
]

students/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required, permission_required
from . import views

app_name = 'students'

urlpatterns = [
   url(r'^login/$', views.LoginView.as_view(), name='login'),
   url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
   url(r'^register/$', views.RegisterView.as_view(), name='register'),
   url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
]

verification/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('everify.urls', namespace='everify')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^institutions/', include('institutions.urls', namespace='institutions')),
]

students/models.py
from django.db import models

# Create your models here.

students/forms.py
import django
from django import forms
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.hashers import identify_hasher
from django.contrib.auth.forms import ReadOnlyPasswordHashField, ReadOnlyPasswordHashWidget, AuthenticationForm as DjangoAuthenticationForm, PasswordResetForm as OldPasswordResetForm
from django.utils.translation import ugettext_lazy as _, ugettext
from django.utils.html import format_html

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field, Fieldset, ButtonHolder
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions


User = get_user_model()


class UserLoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
       
        # user_qs = User.objects.filter(username=username)
        # if user_qs.count() == 1:
        #     user = user_qs.first()
        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect passsword")
            if not user.is_active:
                raise forms.ValidationError("This user is no longer active.")
        return super(UserLoginForm, self).clean(*args, **kwargs)

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-8'
    helper.layout = Layout(
        Field('email', css_class='form-control'),
        Field('password', css_class='form-control'),
        HTML("<hr>"),
        FormActions(
            Submit('register', 'Regster', css_class="btn btn-template-main"),
        )
    )



class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email')
    email2 = forms.EmailField(label='Confirm Email')
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = [
            'name',
            'email',
            'email2',
            'password',
            'password2'
        ]

    def clean_email2(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        return email

    def clean_password2(self, *args, **kwargs):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Passwords must match")
        return password

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-8'
    helper.layout = Layout(
        Field('name', css_class='form-control'),
        Field('email', css_class='form-control'),
        Field('email2', css_class='form-control'),
        Field('password', css_class='form-control'),
        Field('password2', css_class='form-control'),
        #HTML("<hr>"),
        #FormActions(
        #    Submit('register', 'Regster', css_class="btn btn-template-main"),
        #)
    )

students/views.py
import json
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.conf import settings
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import resolve, reverse, reverse_lazy
from django.shortcuts import redirect, render
from django.views import generic
from django.views.generic import FormView, TemplateView, RedirectView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import UserLoginForm, UserRegisterForm

User = get_user_model()


class LoginView(FormView):
    template_name = 'students/student_alumni_login.html'
    form_class = UserLoginForm
    
    def form_valid(self, form):
        if self.request.method == 'POST':
            form = UserLoginForm(self.request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("email")
                password = form.cleaned_data.get('password')
                user = authenticate(email=username, password=password)
                if user is not None:
                    login(self.request, user)

        return super(LoginView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        #context['form'] = self.get_form()
        context.update({
            'form': self.get_form(),
        })
        return context
    
    def get_success_url(self):
        return reverse('students:dashboard')

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            return redirect(self.get_success_url())
        return super(LoginView, self).dispatch(*args, **kwargs)

class LogoutView(RedirectView):
    template_name = None
    permanent = False
    
    def get_redirect_url(self, *args, **kwargs):
        super(LogoutView, self).get_redirect_url(*args, **kwargs)
        return reverse('everify:home')

    def get(self, *args, **kwargs):
        logout(self.request)
        # If we have a url to redirect to, do it. Otherwise render the logged-out template.
        if self.get_redirect_url(**kwargs):
            return RedirectView.get(self, *args, **kwargs)
        
        return redirect("/")

class RegisterView(FormView, TemplateView):
    template_name = 'everify/student_register.html'
    form_class = UserRegisterForm
    
    def form_valid(self, form):
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password')
            user.set_password(password)
            user.save()
            new_user = authenticate(username=user.email, password=password)
            login(self.request, new_user)
            
        return super(RegisterView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def get_success_url(self):
        return reverse('students:dashboard')

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            return redirect(self.get_success_url())
        return super(RegisterView, self).dispatch(*args, **kwargs)



#@login_required
#@permission_required('polls.can_vote', raise_exception=True)

#@login_required(login_url='/students/login/')  #redirect_field_name='my_redirect_field'
@method_decorator(login_required(login_url='/students/login/'), name='dispatch')
class DashboardView(generic.TemplateView):
    model = None
    template_name = 'students/dashboard_student.html'

students/templates/students/dashboard_student.html
<!DOCTYPE html>
<html lang="en">
  {% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Student | Alumni</title>

    <!-- Bootstrap CSS -->    
    <link href="{% static 'everify/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'everify/css/bootstrap-theme.css' %}" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="{% static 'everify/css/elegant-icons-style.css' %}" rel="stylesheet" />
    <link href="{% static 'everify/css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- Custom styles -->
    <link href="{% static 'everify/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'everify/css/style-responsive.css' %}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
      <script src="js/lte-ie7.js"></script>
    <![endif]-->
  </head>

  <body>
  <!-- container section start -->
  <section id="container" class="">
      <!--header start-->
      <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
            </div>

            <!--logo start-->
            <a href="dashboard_student.html" class="logo">Student | Alumni <span class="lite">Dashboard</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">
                <!--  search form start -->
                <ul class="nav top-menu">                    
                    <li>
                        <form class="navbar-form">
                            <input class="form-control" placeholder="Search" type="text">
                        </form>
                    </li>                    
                </ul>
                <!--  search form end -->                
            </div>

            <div class="top-nav notification-row">                
                <!-- notificatoin dropdown start-->
                <ul class="nav pull-right top-menu">
                    
                    <!-- user login dropdown start-->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <img alt="" src="{% static '' %}">
                            </span>
                            <span class="username">{{ user.name }}</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu extended logout">
                            <div class="log-arrow-up"></div>
                            <li class="eborder-top">
                                <a href="#"><i class="icon_profile"></i> My Profile</a>
                            </li>
                            <li>
                                <a href="{% url 'students:logout' %}"><i class="icon_key_alt"></i> Log Out</a>
                            </li>
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                </ul>
                <!-- notificatoin dropdown end-->
            </div>
      </header>      
      <!--header end-->

      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu">                
                  <li class="active">
                      <a class="" href="dashboard_student.html">
                          <i class="icon_house_alt"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>
                  <li>                     
                      <a class="" href="#">
                          <i class="icon_document_alt"></i>
                          <span>My Documents</span>
                          
                      </a>
                                         
                  </li>
                  <li>                     
                      <a class="" href="#">
                          <i class="icon_document_alt"></i>
                          <span>Upload Documents</span>
                          
                      </a>
                                         
                  </li>
                  <li>                     
                      <a class="" href="#">
                          <i class="icon_document_alt"></i>
                          <span>Send Verified Copies</span>
                          
                      </a>
                                         
                  </li>
                  <li class="sub-menu">
                      <a href="javascript:;" class="">
                          <i class="icon_document_alt"></i>
                          <span>Recent</span>
                          <span class="menu-arrow arrow_carrot-right"></span>
                      </a>
                      <ul class="sub">
                          <li><a class="" href="#">Resent Verification</a></li>                          
                          <li><a class="" href="#">Recent Submissions</a></li>
                      </ul>
                  </li>   
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->

      <!--main content start-->
      {% block content %}
      {% endblock %}
      <!--main content end-->
  </section>
  <!-- container section end -->

    <!-- javascripts -->
    <script src="{% static 'everify/js/jquery.js' %}"></script>
    <script src="{% static 'everify/js/bootstrap.min.js' %}"></script>
    <!-- nice scroll -->
    <script src="{% static 'everify/js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'everify/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <!-- jquery validate js -->
    <script type="text/javascript" src="{% static 'everify/js/jquery.validate.min.js' %}"></script>

    <!-- custom form validation script for this page-->
    <script src="{% static 'everify/js/form-validation-script.js' %}"></script>
    <!--custome script for all page-->
    <script src="{% static 'everify/js/scripts.js' %}"></script>    


  </body>
</html>

students/templates/students/student_alumni_login.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load crispy_forms_tags %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Login Page 2 | Creative - Bootstrap 3 Responsive Admin Template</title>

    <!-- Bootstrap CSS -->    
    <link href="{% static 'everify/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'everify/css/bootstrap-theme.css' %}" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="{% static 'everify/css/elegant-icons-style.css' %}" rel="stylesheet" />
    <link href="{% static 'everify/css/font-awesome.css' %}" rel="stylesheet %" />
    <!-- Custom styles -->
    <link href="{% static 'everify/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'everify/css/style-responsive.css' %}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

  <body class="login-img3-body">

    <div class="container">

      <form class="login-form" action="{% url 'students:login' %}" method="POST"> 
        {% csrf_token %} 
        {{ form.non_field_errors }}     
        <div class="login-wrap">
            <p class="login-img"><i class="icon_lock_alt"></i></p>
            <div class="input-group">
              <span class="input-group-addon"><i class="icon_profile"></i></span>
              <input type="email" class="form-control" name="email" placeholder="email" autofocus>
            </div>
            <div class="input-group">
                <span class="input-group-addon"><i class="icon_key_alt"></i></span>
                <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
                <span class="pull-right"> <a href="#"> Forgot Password?</a></span>
            </label>
            <button class="btn btn-primary btn-lg btn-block" type="submit" value="submit">Login</button>
            <a class="btn btn-info btn-lg btn-block" href="{% url 'students:register' %}">SignUp</a>
        </div>
      </form>

    </div>


  </body>
</html>